# Generated by Django 4.2 on 2023-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=1)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
