# Generated by Django 4.2 on 2023-04-14 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='timestamp',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
