# Generated by Django 4.2 on 2023-04-14 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_win_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 14, 13, 51, 15, 326567, tzinfo=datetime.timezone.utc)),
        ),
    ]
